# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [1]:
import numpy as np

In [12]:
A = np.random.randint(0, high = 100, size = (5, 5))
B = np.random.randint(0, high = 100, size = (5, 5))
C = np.random.randint(0, high = 100, size = (5, 5))
print('A\n', A, '\n')
print('B\n', B, '\n')
print('C\n', C, '\n')
A_dot_B_plus_C = np.dot(A, B + C)
A_dot_B_plus_A_dot_C = np.dot(A, B) + np.dot(A, C)

print('A.(B + C)\n', A_dot_B_plus_C, '\n')
print('A.B + A.C\n', A_dot_B_plus_A_dot_C, '\n')
A_dot_B_plus_C == A_dot_B_plus_A_dot_C

A
 [[51  5 41 64 93]
 [22 62 52  4 54]
 [39 57 53 71 28]
 [29  4 75 10 58]
 [97  6 52 19 43]] 

B
 [[39 23 23 37 45]
 [12 88 79 44  6]
 [ 1 67 30 24 39]
 [81 57 36 88 95]
 [96  3 28 41 64]] 

C
 [[90 60 91 56 92]
 [45 59 70 38 64]
 [72 35 63 86 80]
 [84 73 59 40 82]
 [33 27 43  3 53]] 

A.(B + C)
 [[32414 20260 23055 21947 34425]
 [17794 18384 20796 15738 20568]
 [27476 27092 26601 24451 31483]
 [18576 13685 15945 15107 21734]
 [25333 17997 21646 19557 28291]] 

A.B + A.C
 [[32414 20260 23055 21947 34425]
 [17794 18384 20796 15738 20568]
 [27476 27092 26601 24451 31483]
 [18576 13685 15945 15107 21734]
 [25333 17997 21646 19557 28291]] 



array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [13]:
A_dot_B_dot_C = np.dot(A, np.dot(B, C))
A_dot_B_dot_C_two = np.dot(np.dot(A, B), C)

print('A.(B.C)\n', A_dot_B_dot_C, '\n')
print('(A.B).C\n', A_dot_B_dot_C_two, '\n')
A_dot_B_dot_C == A_dot_B_dot_C_two

A.(B.C)
 [[3965499 3076703 3965682 2434242 4511052]
 [2564202 2043834 2628044 1832078 2964178]
 [3797394 3069589 3866531 2546885 4388515]
 [2191980 1742150 2253844 1413026 2543658]
 [2719713 2149390 2756745 1722990 3132378]] 

(A.B).C
 [[3965499 3076703 3965682 2434242 4511052]
 [2564202 2043834 2628044 1832078 2964178]
 [3797394 3069589 3866531 2546885 4388515]
 [2191980 1742150 2253844 1413026 2543658]
 [2719713 2149390 2756745 1722990 3132378]] 



array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [14]:
A_dot_B = np.dot(A, B)
B_dot_A = np.dot(B, A)

print('A.B\n', A_dot_B, '\n')
print('B.A\n', B_dot_A, '\n')
A_dot_B == B_dot_A

A.B
 [[16202  8287  7706 12536 15956]
 [ 7162  9836  8620  7356  7226]
 [10697 13595 10330 12619 12701]
 [ 7632  6788  5217  6307  8916]
 [ 9574  7455  6153  8536 10986]] 

B.A
 [[ 8830  3350  9129  5446  9594]
 [ 7487 10231 12867  7283 10890]
 [ 7174  6199  8943  3443  7620]
 [18556  6913 19733 10653 20808]
 [13451  2810 11979  9770 15004]] 



array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [33]:
x = np.random.randint(0, high=100, size=(3, 1))
y = np.random.randint(0, high=100, size=(3, 1))

print('X\n', x, '\n')
print('X-Transposed\n', x.transpose(), '\n')
print('Y\n', y, '\n')
print('Y-Transposed\n', y.transpose(), '\n')

xT_dot_y = np.dot(x.transpose(), y)
yT_dot_x = np.dot(y.transpose(), x)

print('xT.y\n', xT_dot_y, '\n')
print('yT.x\n', yT_dot_x, '\n')
xT_dot_y == yT_dot_x

X
 [[36]
 [89]
 [79]] 

X-Transposed
 [[36 89 79]] 

Y
 [[63]
 [54]
 [60]] 

Y-Transposed
 [[63 54 60]] 

xT.y
 [[11814]] 

yT.x
 [[11814]] 



array([[ True]])

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [37]:
A_dot_B_trans = np.dot(A, B).transpose()
B_trans_dot_A_trans = np.dot(B.transpose(), A.transpose())

print('(A.B)T \n', A_dot_B_trans, '\n')
print('BT.AT\n', B_trans_dot_A_trans, '\n')
A_dot_B_trans == B_trans_dot_A_trans

(A.B)T 
 [[16202  7162 10697  7632  9574]
 [ 8287  9836 13595  6788  7455]
 [ 7706  8620 10330  5217  6153]
 [12536  7356 12619  6307  8536]
 [15956  7226 12701  8916 10986]] 

BT.AT
 [[16202  7162 10697  7632  9574]
 [ 8287  9836 13595  6788  7455]
 [ 7706  8620 10330  5217  6153]
 [12536  7356 12619  6307  8536]
 [15956  7226 12701  8916 10986]] 



array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 